import { Space } from '@/types/space.types'

export type CategoryType = {
  name: string
  href: string
  description: string
}

export type SectionType = {
  name: string
  features: Array<{
    name: string
    categories: {
      [key in string]: boolean | string
    }
  }>
}

export const sessionsAndLink: CategoryType[] = [
  {
    name: 'Sessions',
    href: `/${Space.AWELL_ORCHESTRATION}/docs/activities/awell-hosted-pages/hosted-pathway-guide`,
    description: `Create a session via Awell's API`,
  },
  {
    name: 'Links',
    href: `/${Space.AWELL_ORCHESTRATION}/docs/activities/awell-hosted-pages/hosted-activity-guide`,
    description: 'Get a shareable link generated by Awell',
  },
]

export const sections: SectionType[] = [
  {
    name: 'How it works',
    features: [
      {
        name: 'Created by',
        categories: {
          Sessions: "You, via Awell's API",
          Links: 'Awell',
        },
      },
      {
        name: 'Expiration',
        categories: {
          Sessions: 'Yes, after 60 minutes',
          Links: 'No, never',
        },
      },
    ],
  },
]
