export type ButtonSizeType = 'xs' | 'sm' | 'base' | 'lg' | 'xl'
export type ButtonColorType =
  | 'white'
  | 'purple'
  | 'emerald'
  | 'amber'
  | 'pink'
  | 'blue'
  | 'lime'
  | 'slate'
export type ButtonShadowDirectionType = 'ltr' | 'rtl'
export type ButtonType = 'button' | 'submit'