export { beautifySnakeCase } from './beautifySnakeCase'
export { capitalizeFirstLetter } from './capitalizeFirstLetter'
export { removeLeadingAndTrailingSlashes } from './removeLeadingAndTrailingSlashes'
export { stripHtml } from './stripHtml'
export { truncate } from './truncate'
