export { getAllApiDocs, getApiDoc } from './apiReferenceUtils'
export { capitalizeFirstLetter } from './capitalizeFirstLetter'
export { getAllDocs, getDoc } from './docsUtils'
export { getBadeForDoc } from './getBadgeForDoc'
export { getCurrentYear } from './getCurrentYear'
export { getHeadingForDoc } from './getHeadingForDoc'
export { getTableOfContents } from './getTableOfContents'
export { removeLeadingAndTrailingSlashes } from './removeLeadingAndTrailingSlashes'
