export { getAllApiDocs, getApiDoc } from './apiReferenceUtils'
export { getAllDocs, getDoc } from './docsUtils'
export { getCurrentYear } from './getCurrentYear'
export { getHeadingForDoc } from './getHeadingForDoc'
export { getTableOfContents } from './getTableOfConents'
export { removeLeadingAndTrailingSlashes } from './removeLeadingAndTrailingSlashes'
